<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Controllers\OrdersController.cs" />
    <Compile Include="DTOs\OrderCreateResponse.cs" />
    <Compile Include="Models\OrderRequest.cs" />
    <Compile Include="Models\Order.cs" />
    <Compile Include="Models\OrderItem.cs" />
    <Compile Include="Models\Customer.cs" />
    <Compile Include="Models\Product.cs" />
    <Compile Include="Models\OrderHistory.cs" />
    <Compile Include="Models\AuditLog.cs" />
    <Compile Include="Models\AppDbContext.cs" />
    <Compile Include="Repositories\IOrderRepository.cs" />
    <Compile Include="Repositories\OrderRepository.cs" />
    <Compile Include="Services\IOrderService.cs" />
    <Compile Include="Services\IShippingStrategy.cs" />
    <Compile Include="Services\DefaultShippingStrategy.cs" />
    <Compile Include="Services\ITaxStrategy.cs" />
    <Compile Include="Services\DefaultTaxStrategy.cs" />
    <Compile Include="Services\IDiscountStrategy.cs" />
    <Compile Include="Services\DefaultDiscountStrategy.cs" />
    <Compile Include="Services\OrderService.cs" />
  </ItemGroup>

</Project>
